# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ascom_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AscomDialog(object):
    def setupUi(self, AscomDialog):
        AscomDialog.setObjectName("AscomDialog")
        AscomDialog.resize(542, 238)
        AscomDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AscomDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(AscomDialog)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 520, 185))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 511, 164))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.select_driver = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.select_driver.setFont(font)
        self.select_driver.setObjectName("select_driver")
        self.gridLayout.addWidget(self.select_driver, 0, 0, 1, 2)
        self.guiding_interval = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.guiding_interval.setFont(font)
        self.guiding_interval.setObjectName("guiding_interval")
        self.gridLayout.addWidget(self.guiding_interval, 1, 0, 1, 1)
        self.input_guiding_interval = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_guiding_interval.setFont(font)
        self.input_guiding_interval.setObjectName("input_guiding_interval")
        self.gridLayout.addWidget(self.input_guiding_interval, 1, 1, 1, 1)
        self.wait_interval = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wait_interval.setFont(font)
        self.wait_interval.setObjectName("wait_interval")
        self.gridLayout.addWidget(self.wait_interval, 3, 0, 1, 1)
        self.input_wait_interval = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_wait_interval.setFont(font)
        self.input_wait_interval.setObjectName("input_wait_interval")
        self.gridLayout.addWidget(self.input_wait_interval, 3, 1, 1, 1)
        self.telescope_lookup_precision = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.telescope_lookup_precision.setFont(font)
        self.telescope_lookup_precision.setObjectName("telescope_lookup_precision")
        self.gridLayout.addWidget(self.telescope_lookup_precision, 5, 0, 1, 1)
        self.input_telescope_lookup_precision = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_telescope_lookup_precision.setFont(font)
        self.input_telescope_lookup_precision.setObjectName("input_telescope_lookup_precision")
        self.gridLayout.addWidget(self.input_telescope_lookup_precision, 5, 1, 1, 1)
        self.pulse_guide_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse_guide_speed.setFont(font)
        self.pulse_guide_speed.setObjectName("pulse_guide_speed")
        self.gridLayout.addWidget(self.pulse_guide_speed, 2, 0, 1, 1)
        self.input_pulse_guide_speed = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pulse_guide_speed.setFont(font)
        self.input_pulse_guide_speed.setToolTip("")
        self.input_pulse_guide_speed.setObjectName("input_pulse_guide_speed")
        self.gridLayout.addWidget(self.input_pulse_guide_speed, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(AscomDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(AscomDialog)
        self.buttonBox.accepted.connect(AscomDialog.accept)
        self.buttonBox.rejected.connect(AscomDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AscomDialog)
        AscomDialog.setTabOrder(self.scrollArea, self.buttonBox)

    def retranslateUi(self, AscomDialog):
        _translate = QtCore.QCoreApplication.translate
        AscomDialog.setWindowTitle(_translate("AscomDialog", "Configure ASCOM telescope interface"))
        self.select_driver.setToolTip(_translate("AscomDialog", "Open the ASCOM telescope driver chooser. Do not forget to configure the driver."))
        self.select_driver.setText(_translate("AscomDialog", "Select and configure the ASCOM telescope driver"))
        self.guiding_interval.setToolTip(_translate("AscomDialog", "Duration of guiding pulses during video exposure, e.g. 0.2. Must be between 0. and 3."))
        self.guiding_interval.setText(_translate("AscomDialog", "Guide pulse duration (s)"))
        self.wait_interval.setToolTip(_translate("AscomDialog", "Parameter to reduce polling frequency during telescope slewing, e.g. 1. Must be between 0. and 20."))
        self.wait_interval.setText(_translate("AscomDialog", "Wait interval (s)"))
        self.telescope_lookup_precision.setToolTip(_translate("AscomDialog", "Required precision (\") for lookup of telescope position. Must be between 0.1 and 10."))
        self.telescope_lookup_precision.setText(_translate("AscomDialog", "Telescope position lookup precision (\")   "))
        self.pulse_guide_speed.setToolTip(_translate("AscomDialog", "Speed of pulse guide operations in RA/DE. Must be between 0. and 1."))
        self.pulse_guide_speed.setText(_translate("AscomDialog", "Pulse guide speed (deg/sec)"))
        self.buttonBox.setToolTip(_translate("AscomDialog", "Save or discard new input"))

