# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_dialog.ui'
#
# Created: Mon Aug 24 14:40:24 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CameraDialog(object):
    def setupUi(self, CameraDialog):
        CameraDialog.setObjectName(_fromUtf8("CameraDialog"))
        CameraDialog.resize(571, 333)
        CameraDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtGui.QVBoxLayout(CameraDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(CameraDialog)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 547, 274))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.input_tile_overlap = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_tile_overlap.setFont(font)
        self.input_tile_overlap.setObjectName(_fromUtf8("input_tile_overlap"))
        self.gridLayout.addWidget(self.input_tile_overlap, 6, 1, 1, 1)
        self.input_pixel_horizontal = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_horizontal.setFont(font)
        self.input_pixel_horizontal.setObjectName(_fromUtf8("input_pixel_horizontal"))
        self.gridLayout.addWidget(self.input_pixel_horizontal, 3, 1, 1, 1)
        self.external_margin = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.external_margin.setFont(font)
        self.external_margin.setObjectName(_fromUtf8("external_margin"))
        self.gridLayout.addWidget(self.external_margin, 5, 0, 1, 1)
        self.input_pixel_size = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_size.setFont(font)
        self.input_pixel_size.setObjectName(_fromUtf8("input_pixel_size"))
        self.gridLayout.addWidget(self.input_pixel_size, 2, 1, 1, 1)
        self.name = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.input_pixel_vertical = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_vertical.setFont(font)
        self.input_pixel_vertical.setObjectName(_fromUtf8("input_pixel_vertical"))
        self.gridLayout.addWidget(self.input_pixel_vertical, 4, 1, 1, 1)
        self.input_external_margin = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_external_margin.setFont(font)
        self.input_external_margin.setObjectName(_fromUtf8("input_external_margin"))
        self.gridLayout.addWidget(self.input_external_margin, 5, 1, 1, 1)
        self.tile_overlap = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tile_overlap.setFont(font)
        self.tile_overlap.setObjectName(_fromUtf8("tile_overlap"))
        self.gridLayout.addWidget(self.tile_overlap, 6, 0, 1, 1)
        self.pixel_vertical = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_vertical.setFont(font)
        self.pixel_vertical.setObjectName(_fromUtf8("pixel_vertical"))
        self.gridLayout.addWidget(self.pixel_vertical, 4, 0, 1, 1)
        self.Camera = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Camera.setFont(font)
        self.Camera.setObjectName(_fromUtf8("Camera"))
        self.gridLayout.addWidget(self.Camera, 0, 0, 1, 1)
        self.pixel_horizontal = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_horizontal.setFont(font)
        self.pixel_horizontal.setObjectName(_fromUtf8("pixel_horizontal"))
        self.gridLayout.addWidget(self.pixel_horizontal, 3, 0, 1, 1)
        self.pixel_size = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_size.setFont(font)
        self.pixel_size.setObjectName(_fromUtf8("pixel_size"))
        self.gridLayout.addWidget(self.pixel_size, 2, 0, 1, 1)
        self.input_camera_name = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_camera_name.setFont(font)
        self.input_camera_name.setObjectName(_fromUtf8("input_camera_name"))
        self.gridLayout.addWidget(self.input_camera_name, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonBox = QtGui.QDialogButtonBox(CameraDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CameraDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CameraDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CameraDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CameraDialog)
        CameraDialog.setTabOrder(self.scrollArea, self.input_camera_name)
        CameraDialog.setTabOrder(self.input_camera_name, self.input_pixel_size)
        CameraDialog.setTabOrder(self.input_pixel_size, self.input_pixel_horizontal)
        CameraDialog.setTabOrder(self.input_pixel_horizontal, self.input_pixel_vertical)
        CameraDialog.setTabOrder(self.input_pixel_vertical, self.input_external_margin)
        CameraDialog.setTabOrder(self.input_external_margin, self.input_tile_overlap)
        CameraDialog.setTabOrder(self.input_tile_overlap, self.buttonBox)

    def retranslateUi(self, CameraDialog):
        CameraDialog.setWindowTitle(QtGui.QApplication.translate("CameraDialog", "Configure Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.external_margin.setToolTip(QtGui.QApplication.translate("CameraDialog", "Minimum width of dark area around Moon to be recorded, in pixels. Must be between 1 and 10000", None, QtGui.QApplication.UnicodeUTF8))
        self.external_margin.setText(QtGui.QApplication.translate("CameraDialog", "External margin pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.name.setToolTip(QtGui.QApplication.translate("CameraDialog", "Any text to represent camera, must be unique in list", None, QtGui.QApplication.UnicodeUTF8))
        self.name.setText(QtGui.QApplication.translate("CameraDialog", "Brand / Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tile_overlap.setToolTip(QtGui.QApplication.translate("CameraDialog", "Minimum overlap between tiles in pixels, must be between 1 and 5000", None, QtGui.QApplication.UnicodeUTF8))
        self.tile_overlap.setText(QtGui.QApplication.translate("CameraDialog", "Tile overlap pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_vertical.setToolTip(QtGui.QApplication.translate("CameraDialog", "Number of vertical sensor pixels, must be between 0 and 20000", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_vertical.setText(QtGui.QApplication.translate("CameraDialog", "Pixel count vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.Camera.setText(QtGui.QApplication.translate("CameraDialog", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_horizontal.setToolTip(QtGui.QApplication.translate("CameraDialog", "Number of horizontal sensor pixels, must be between 0 and 20000", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_horizontal.setText(QtGui.QApplication.translate("CameraDialog", "Pixel count horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_size.setToolTip(QtGui.QApplication.translate("CameraDialog", "Camera pixel size in mm (not micrometers), must be between 0. and 0.02", None, QtGui.QApplication.UnicodeUTF8))
        self.pixel_size.setText(QtGui.QApplication.translate("CameraDialog", "Pixel size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setToolTip(QtGui.QApplication.translate("CameraDialog", "Save or discard new input", None, QtGui.QApplication.UnicodeUTF8))

