# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CameraDialog(object):
    def setupUi(self, CameraDialog):
        CameraDialog.setObjectName("CameraDialog")
        CameraDialog.resize(571, 333)
        CameraDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CameraDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(CameraDialog)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 280))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pixel_size = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_size.setFont(font)
        self.pixel_size.setObjectName("pixel_size")
        self.gridLayout.addWidget(self.pixel_size, 2, 0, 1, 1)
        self.input_tile_overlap = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_tile_overlap.setFont(font)
        self.input_tile_overlap.setObjectName("input_tile_overlap")
        self.gridLayout.addWidget(self.input_tile_overlap, 7, 2, 1, 1)
        self.input_pixel_horizontal = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_horizontal.setFont(font)
        self.input_pixel_horizontal.setObjectName("input_pixel_horizontal")
        self.gridLayout.addWidget(self.input_pixel_horizontal, 3, 2, 1, 1)
        self.external_margin = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.external_margin.setFont(font)
        self.external_margin.setObjectName("external_margin")
        self.gridLayout.addWidget(self.external_margin, 6, 0, 1, 1)
        self.input_pixel_size = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_size.setFont(font)
        self.input_pixel_size.setObjectName("input_pixel_size")
        self.gridLayout.addWidget(self.input_pixel_size, 2, 2, 1, 1)
        self.name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.input_pixel_vertical = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_pixel_vertical.setFont(font)
        self.input_pixel_vertical.setObjectName("input_pixel_vertical")
        self.gridLayout.addWidget(self.input_pixel_vertical, 4, 2, 1, 1)
        self.input_external_margin = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_external_margin.setFont(font)
        self.input_external_margin.setObjectName("input_external_margin")
        self.gridLayout.addWidget(self.input_external_margin, 6, 2, 1, 1)
        self.tile_overlap = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tile_overlap.setFont(font)
        self.tile_overlap.setObjectName("tile_overlap")
        self.gridLayout.addWidget(self.tile_overlap, 7, 0, 1, 1)
        self.pixel_vertical = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_vertical.setFont(font)
        self.pixel_vertical.setObjectName("pixel_vertical")
        self.gridLayout.addWidget(self.pixel_vertical, 4, 0, 1, 1)
        self.Camera = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Camera.setFont(font)
        self.Camera.setObjectName("Camera")
        self.gridLayout.addWidget(self.Camera, 0, 0, 1, 1)
        self.pixel_horizontal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pixel_horizontal.setFont(font)
        self.pixel_horizontal.setObjectName("pixel_horizontal")
        self.gridLayout.addWidget(self.pixel_horizontal, 3, 0, 1, 1)
        self.input_camera_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_camera_name.setFont(font)
        self.input_camera_name.setObjectName("input_camera_name")
        self.gridLayout.addWidget(self.input_camera_name, 1, 2, 1, 1)
        self.repetition_count = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.repetition_count.setFont(font)
        self.repetition_count.setObjectName("repetition_count")
        self.gridLayout.addWidget(self.repetition_count, 5, 0, 1, 1)
        self.input_repetition_count = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_repetition_count.setFont(font)
        self.input_repetition_count.setObjectName("input_repetition_count")
        self.gridLayout.addWidget(self.input_repetition_count, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(CameraDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(CameraDialog)
        self.buttonBox.accepted.connect(CameraDialog.accept)
        self.buttonBox.rejected.connect(CameraDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CameraDialog)
        CameraDialog.setTabOrder(self.scrollArea, self.input_camera_name)
        CameraDialog.setTabOrder(self.input_camera_name, self.input_pixel_size)
        CameraDialog.setTabOrder(self.input_pixel_size, self.input_pixel_horizontal)
        CameraDialog.setTabOrder(self.input_pixel_horizontal, self.input_pixel_vertical)
        CameraDialog.setTabOrder(self.input_pixel_vertical, self.input_repetition_count)
        CameraDialog.setTabOrder(self.input_repetition_count, self.input_external_margin)
        CameraDialog.setTabOrder(self.input_external_margin, self.input_tile_overlap)
        CameraDialog.setTabOrder(self.input_tile_overlap, self.buttonBox)

    def retranslateUi(self, CameraDialog):
        _translate = QtCore.QCoreApplication.translate
        CameraDialog.setWindowTitle(_translate("CameraDialog", "Configure Camera"))
        self.pixel_size.setToolTip(_translate("CameraDialog", "Camera pixel size in mm (not micrometers), must be between 0. and 0.02"))
        self.pixel_size.setText(_translate("CameraDialog", "Pixel size (mm)"))
        self.external_margin.setToolTip(_translate("CameraDialog", "Minimum width of dark area around Moon to be recorded, in pixels. Must be between 1 and 10000"))
        self.external_margin.setText(_translate("CameraDialog", "External margin pixels"))
        self.name.setToolTip(_translate("CameraDialog", "Any text to represent camera, must be unique in list"))
        self.name.setText(_translate("CameraDialog", "Brand / Name"))
        self.tile_overlap.setToolTip(_translate("CameraDialog", "Minimum overlap between tiles in pixels, must be between 1 and 5000"))
        self.tile_overlap.setText(_translate("CameraDialog", "Tile overlap pixels"))
        self.pixel_vertical.setToolTip(_translate("CameraDialog", "Number of vertical sensor pixels, must be between 0 and 20000"))
        self.pixel_vertical.setText(_translate("CameraDialog", "Pixel count vertical"))
        self.Camera.setText(_translate("CameraDialog", "Camera"))
        self.pixel_horizontal.setToolTip(_translate("CameraDialog", "Number of horizontal sensor pixels, must be between 0 and 20000"))
        self.pixel_horizontal.setText(_translate("CameraDialog", "Pixel count horizontal"))
        self.repetition_count.setText(_translate("CameraDialog", "Repetition count"))
        self.buttonBox.setToolTip(_translate("CameraDialog", "Save or discard new input"))

