# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigurationDialog(object):
    def setupUi(self, ConfigurationDialog):
        ConfigurationDialog.setObjectName("ConfigurationDialog")
        ConfigurationDialog.resize(624, 822)
        font = QtGui.QFont()
        font.setPointSize(10)
        ConfigurationDialog.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(ConfigurationDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(ConfigurationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 602, 766))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(9, -1, 9, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 6, 0, 1, 1)
        self.longitude = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.longitude.setFont(font)
        self.longitude.setObjectName("longitude")
        self.gridLayout.addWidget(self.longitude, 1, 0, 1, 1)
        self.timezone = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timezone.setFont(font)
        self.timezone.setObjectName("timezone")
        self.gridLayout.addWidget(self.timezone, 4, 0, 1, 1)
        self.camera_automation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_automation.sizePolicy().hasHeightForWidth())
        self.camera_automation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.camera_automation.setFont(font)
        self.camera_automation.setObjectName("camera_automation")
        self.gridLayout.addWidget(self.camera_automation, 16, 0, 1, 1)
        self.telescope = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.telescope.setFont(font)
        self.telescope.setObjectName("telescope")
        self.gridLayout.addWidget(self.telescope, 8, 0, 1, 1)
        self.limb_first = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.limb_first.setFont(font)
        self.limb_first.setObjectName("limb_first")
        self.gridLayout.addWidget(self.limb_first, 15, 0, 1, 1)
        self.fig_size_horizontal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_size_horizontal.sizePolicy().hasHeightForWidth())
        self.fig_size_horizontal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fig_size_horizontal.setFont(font)
        self.fig_size_horizontal.setObjectName("fig_size_horizontal")
        self.gridLayout.addWidget(self.fig_size_horizontal, 19, 0, 1, 1)
        self.tile_visualization = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tile_visualization.setFont(font)
        self.tile_visualization.setObjectName("tile_visualization")
        self.gridLayout.addWidget(self.tile_visualization, 18, 0, 1, 1)
        self.min_autoalign_interval = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.min_autoalign_interval.setFont(font)
        self.min_autoalign_interval.setObjectName("min_autoalign_interval")
        self.gridLayout.addWidget(self.min_autoalign_interval, 25, 0, 1, 1)
        self.input_elevation = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_elevation.setFont(font)
        self.input_elevation.setObjectName("input_elevation")
        self.gridLayout.addWidget(self.input_elevation, 3, 2, 1, 4)
        self.max_alignment_error = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_alignment_error.setFont(font)
        self.max_alignment_error.setObjectName("max_alignment_error")
        self.gridLayout.addWidget(self.max_alignment_error, 27, 0, 1, 1)
        self.focus_on_star = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focus_on_star.setFont(font)
        self.focus_on_star.setObjectName("focus_on_star")
        self.gridLayout.addWidget(self.focus_on_star, 14, 0, 1, 1)
        self.protocol_to_file = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.protocol_to_file.setFont(font)
        self.protocol_to_file.setObjectName("protocol_to_file")
        self.gridLayout.addWidget(self.protocol_to_file, 13, 0, 1, 1)
        self.camera_trigger_delay = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.camera_trigger_delay.setFont(font)
        self.camera_trigger_delay.setObjectName("camera_trigger_delay")
        self.gridLayout.addWidget(self.camera_trigger_delay, 17, 0, 1, 1)
        self.elevation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.elevation.setFont(font)
        self.elevation.setObjectName("elevation")
        self.gridLayout.addWidget(self.elevation, 3, 0, 1, 1)
        self.camera = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setObjectName("camera")
        self.gridLayout.addWidget(self.camera, 5, 0, 1, 1)
        self.label_shift = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_shift.setFont(font)
        self.label_shift.setObjectName("label_shift")
        self.gridLayout.addWidget(self.label_shift, 22, 0, 1, 1)
        self.protocol_level = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.protocol_level.setFont(font)
        self.protocol_level.setObjectName("protocol_level")
        self.gridLayout.addWidget(self.protocol_level, 12, 0, 1, 1)
        self.ALIGNMENT = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ALIGNMENT.setFont(font)
        self.ALIGNMENT.setObjectName("ALIGNMENT")
        self.gridLayout.addWidget(self.ALIGNMENT, 24, 0, 1, 1)
        self.new_camera = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_camera.sizePolicy().hasHeightForWidth())
        self.new_camera.setSizePolicy(sizePolicy)
        self.new_camera.setMinimumSize(QtCore.QSize(0, 0))
        self.new_camera.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_camera.setFont(font)
        self.new_camera.setObjectName("new_camera")
        self.gridLayout.addWidget(self.new_camera, 6, 4, 1, 1)
        self.delete_camera = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_camera.sizePolicy().hasHeightForWidth())
        self.delete_camera.setSizePolicy(sizePolicy)
        self.delete_camera.setMinimumSize(QtCore.QSize(0, 0))
        self.delete_camera.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_camera.setFont(font)
        self.delete_camera.setObjectName("delete_camera")
        self.gridLayout.addWidget(self.delete_camera, 6, 5, 1, 1)
        self.input_latitude = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_latitude.setFont(font)
        self.input_latitude.setObjectName("input_latitude")
        self.gridLayout.addWidget(self.input_latitude, 2, 2, 1, 4)
        self.geographical_position = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.geographical_position.setFont(font)
        self.geographical_position.setObjectName("geographical_position")
        self.gridLayout.addWidget(self.geographical_position, 0, 0, 1, 1)
        self.input_focal_length = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_focal_length.setFont(font)
        self.input_focal_length.setObjectName("input_focal_length")
        self.gridLayout.addWidget(self.input_focal_length, 9, 2, 1, 4)
        self.input_longitude = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_longitude.setFont(font)
        self.input_longitude.setObjectName("input_longitude")
        self.gridLayout.addWidget(self.input_longitude, 1, 2, 1, 4)
        self.edit_camera = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_camera.sizePolicy().hasHeightForWidth())
        self.edit_camera.setSizePolicy(sizePolicy)
        self.edit_camera.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_camera.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edit_camera.setFont(font)
        self.edit_camera.setObjectName("edit_camera")
        self.gridLayout.addWidget(self.edit_camera, 6, 3, 1, 1)
        self.focal_length = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focal_length.setFont(font)
        self.focal_length.setObjectName("focal_length")
        self.gridLayout.addWidget(self.focal_length, 9, 0, 1, 1)
        self.latitude = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.latitude.setFont(font)
        self.latitude.setObjectName("latitude")
        self.gridLayout.addWidget(self.latitude, 2, 0, 1, 1)
        self.fig_size_vertical = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fig_size_vertical.setFont(font)
        self.fig_size_vertical.setObjectName("fig_size_vertical")
        self.gridLayout.addWidget(self.fig_size_vertical, 20, 0, 1, 1)
        self.workflow = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.workflow.setFont(font)
        self.workflow.setObjectName("workflow")
        self.gridLayout.addWidget(self.workflow, 11, 0, 1, 1)
        self.camera_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.camera_chooser.setFont(font)
        self.camera_chooser.setObjectName("camera_chooser")
        self.gridLayout.addWidget(self.camera_chooser, 6, 2, 1, 1)
        self.max_autoalign_interval = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.max_autoalign_interval.setFont(font)
        self.max_autoalign_interval.setObjectName("max_autoalign_interval")
        self.gridLayout.addWidget(self.max_autoalign_interval, 26, 0, 1, 1)
        self.label_font_size = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_font_size.setFont(font)
        self.label_font_size.setObjectName("label_font_size")
        self.gridLayout.addWidget(self.label_font_size, 21, 0, 1, 1)
        self.telescope_interface = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.telescope_interface.setFont(font)
        self.telescope_interface.setObjectName("telescope_interface")
        self.gridLayout.addWidget(self.telescope_interface, 10, 0, 1, 1)
        self.mount_interface_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mount_interface_chooser.setFont(font)
        self.mount_interface_chooser.setObjectName("mount_interface_chooser")
        self.gridLayout.addWidget(self.mount_interface_chooser, 10, 2, 1, 1)
        self.configure_mount_interface = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.configure_mount_interface.setFont(font)
        self.configure_mount_interface.setObjectName("configure_mount_interface")
        self.gridLayout.addWidget(self.configure_mount_interface, 10, 3, 1, 3)
        self.ip_address = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ip_address.setFont(font)
        self.ip_address.setStatusTip("")
        self.ip_address.setObjectName("ip_address")
        self.gridLayout.addWidget(self.ip_address, 7, 0, 1, 1)
        self.input_ip_address = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_ip_address.setFont(font)
        self.input_ip_address.setObjectName("input_ip_address")
        self.gridLayout.addWidget(self.input_ip_address, 7, 2, 1, 4)
        self.timezone_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timezone_chooser.setFont(font)
        self.timezone_chooser.setMaxVisibleItems(20)
        self.timezone_chooser.setObjectName("timezone_chooser")
        self.gridLayout.addWidget(self.timezone_chooser, 4, 2, 1, 4)
        self.protocol_level_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.protocol_level_chooser.setObjectName("protocol_level_chooser")
        self.gridLayout.addWidget(self.protocol_level_chooser, 12, 2, 1, 1)
        self.input_fig_size_horizontal = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_fig_size_horizontal.setFont(font)
        self.input_fig_size_horizontal.setObjectName("input_fig_size_horizontal")
        self.gridLayout.addWidget(self.input_fig_size_horizontal, 19, 2, 1, 1)
        self.input_fig_size_vertical = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_fig_size_vertical.setFont(font)
        self.input_fig_size_vertical.setObjectName("input_fig_size_vertical")
        self.gridLayout.addWidget(self.input_fig_size_vertical, 20, 2, 1, 1)
        self.input_label_font_size = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_label_font_size.setFont(font)
        self.input_label_font_size.setObjectName("input_label_font_size")
        self.gridLayout.addWidget(self.input_label_font_size, 21, 2, 1, 1)
        self.input_label_shift = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_label_shift.setFont(font)
        self.input_label_shift.setObjectName("input_label_shift")
        self.gridLayout.addWidget(self.input_label_shift, 22, 2, 1, 1)
        self.input_min_autoalign_interval = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.input_min_autoalign_interval.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_min_autoalign_interval.setFont(font)
        self.input_min_autoalign_interval.setObjectName("input_min_autoalign_interval")
        self.gridLayout.addWidget(self.input_min_autoalign_interval, 25, 2, 1, 1)
        self.input_max_autoalign_interval = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_max_autoalign_interval.setFont(font)
        self.input_max_autoalign_interval.setObjectName("input_max_autoalign_interval")
        self.gridLayout.addWidget(self.input_max_autoalign_interval, 26, 2, 1, 1)
        self.input_max_alignment_error = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_max_alignment_error.setFont(font)
        self.input_max_alignment_error.setObjectName("input_max_alignment_error")
        self.gridLayout.addWidget(self.input_max_alignment_error, 27, 2, 1, 1)
        self.protocol_to_file_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.protocol_to_file_chooser.setFont(font)
        self.protocol_to_file_chooser.setToolTip("")
        self.protocol_to_file_chooser.setObjectName("protocol_to_file_chooser")
        self.gridLayout.addWidget(self.protocol_to_file_chooser, 13, 2, 1, 4)
        self.focus_on_star_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.focus_on_star_chooser.setFont(font)
        self.focus_on_star_chooser.setToolTip("")
        self.focus_on_star_chooser.setObjectName("focus_on_star_chooser")
        self.gridLayout.addWidget(self.focus_on_star_chooser, 14, 2, 1, 4)
        self.limb_first_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.limb_first_chooser.setFont(font)
        self.limb_first_chooser.setToolTip("")
        self.limb_first_chooser.setObjectName("limb_first_chooser")
        self.gridLayout.addWidget(self.limb_first_chooser, 15, 2, 1, 4)
        self.camera_automation_chooser = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.camera_automation_chooser.setFont(font)
        self.camera_automation_chooser.setToolTip("")
        self.camera_automation_chooser.setObjectName("camera_automation_chooser")
        self.gridLayout.addWidget(self.camera_automation_chooser, 16, 2, 1, 4)
        self.input_camera_trigger_delay = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_camera_trigger_delay.setFont(font)
        self.input_camera_trigger_delay.setObjectName("input_camera_trigger_delay")
        self.gridLayout.addWidget(self.input_camera_trigger_delay, 17, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigurationDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ConfigurationDialog)
        self.buttonBox.accepted.connect(ConfigurationDialog.accept)
        self.buttonBox.rejected.connect(ConfigurationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationDialog)
        ConfigurationDialog.setTabOrder(self.scrollArea, self.input_longitude)
        ConfigurationDialog.setTabOrder(self.input_longitude, self.input_latitude)
        ConfigurationDialog.setTabOrder(self.input_latitude, self.input_elevation)
        ConfigurationDialog.setTabOrder(self.input_elevation, self.timezone_chooser)
        ConfigurationDialog.setTabOrder(self.timezone_chooser, self.camera_chooser)
        ConfigurationDialog.setTabOrder(self.camera_chooser, self.edit_camera)
        ConfigurationDialog.setTabOrder(self.edit_camera, self.new_camera)
        ConfigurationDialog.setTabOrder(self.new_camera, self.delete_camera)
        ConfigurationDialog.setTabOrder(self.delete_camera, self.input_ip_address)
        ConfigurationDialog.setTabOrder(self.input_ip_address, self.input_focal_length)
        ConfigurationDialog.setTabOrder(self.input_focal_length, self.mount_interface_chooser)
        ConfigurationDialog.setTabOrder(self.mount_interface_chooser, self.configure_mount_interface)
        ConfigurationDialog.setTabOrder(self.configure_mount_interface, self.protocol_level_chooser)
        ConfigurationDialog.setTabOrder(self.protocol_level_chooser, self.protocol_to_file_chooser)
        ConfigurationDialog.setTabOrder(self.protocol_to_file_chooser, self.focus_on_star_chooser)
        ConfigurationDialog.setTabOrder(self.focus_on_star_chooser, self.limb_first_chooser)
        ConfigurationDialog.setTabOrder(self.limb_first_chooser, self.camera_automation_chooser)
        ConfigurationDialog.setTabOrder(self.camera_automation_chooser, self.input_camera_trigger_delay)
        ConfigurationDialog.setTabOrder(self.input_camera_trigger_delay, self.input_fig_size_horizontal)
        ConfigurationDialog.setTabOrder(self.input_fig_size_horizontal, self.input_fig_size_vertical)
        ConfigurationDialog.setTabOrder(self.input_fig_size_vertical, self.input_label_font_size)
        ConfigurationDialog.setTabOrder(self.input_label_font_size, self.input_label_shift)
        ConfigurationDialog.setTabOrder(self.input_label_shift, self.input_min_autoalign_interval)
        ConfigurationDialog.setTabOrder(self.input_min_autoalign_interval, self.input_max_autoalign_interval)
        ConfigurationDialog.setTabOrder(self.input_max_autoalign_interval, self.input_max_alignment_error)

    def retranslateUi(self, ConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationDialog.setWindowTitle(_translate("ConfigurationDialog", "Confgturation"))
        self.name.setToolTip(_translate("ConfigurationDialog", "Any text to represent camera, must be unique in list"))
        self.name.setText(_translate("ConfigurationDialog", "Brand / Name"))
        self.longitude.setToolTip(_translate("ConfigurationDialog", "Geographical longitude, counted from Greenwich, in degrees plus decimal fraction. Must be between -360. and 360."))
        self.longitude.setText(_translate("ConfigurationDialog", "Longitude (degrees, east positiv)"))
        self.timezone.setToolTip(_translate("ConfigurationDialog", "Choose from list. Daylight saving time is accounted for automatically"))
        self.timezone.setText(_translate("ConfigurationDialog", "Timezone (e.g. Europe/Berlin)"))
        self.camera_automation.setToolTip(_translate("ConfigurationDialog", "The camera can be either triggered manually, or the program triggers FireCapture automatically."))
        self.camera_automation.setText(_translate("ConfigurationDialog", "Camera automation"))
        self.telescope.setText(_translate("ConfigurationDialog", "Telescope"))
        self.limb_first.setToolTip(_translate("ConfigurationDialog", "Choose whether the tiles at the bright moon limb or those near the terminator should be recorded first."))
        self.limb_first.setText(_translate("ConfigurationDialog", "Begin at moon limb or terminator"))
        self.fig_size_horizontal.setToolTip(_translate("ConfigurationDialog", "Horizontal dimension of tile visualization window in inches. Must be between 0. and 25."))
        self.fig_size_horizontal.setText(_translate("ConfigurationDialog", "Figure size horizontal (inch)"))
        self.tile_visualization.setText(_translate("ConfigurationDialog", "Tile Visualization"))
        self.min_autoalign_interval.setToolTip(_translate("ConfigurationDialog", "Minimum time between auto-alignments (s). Must be between 20. and 1800."))
        self.min_autoalign_interval.setText(_translate("ConfigurationDialog", "Minimum auto-alignment interval (s)"))
        self.max_alignment_error.setToolTip(_translate("ConfigurationDialog", "Maximum allowed auto-alignment error (% of overlap width). Must be between 10. and 60."))
        self.max_alignment_error.setText(_translate("ConfigurationDialog", "Max alignment error (%)"))
        self.focus_on_star.setToolTip(_translate("ConfigurationDialog", "The focus can be adjusted on a star or on a lunar feature."))
        self.focus_on_star.setText(_translate("ConfigurationDialog", "Focus on a star or lunar feature"))
        self.protocol_to_file.setToolTip(_translate("ConfigurationDialog", "If \"file\" is selected, append session protocol to file \"MoonPanoramaMaker.log\" in home directory"))
        self.protocol_to_file.setText(_translate("ConfigurationDialog", "Write protocol to file or StdOut"))
        self.camera_trigger_delay.setToolTip(_translate("ConfigurationDialog", "Time between slewing to new tile and exposure start. Must be between 0. and 60."))
        self.camera_trigger_delay.setText(_translate("ConfigurationDialog", "Camera trigger delay (s)"))
        self.elevation.setToolTip(_translate("ConfigurationDialog", "Elevation above sea level in meters. Must be between -100 and 9000"))
        self.elevation.setText(_translate("ConfigurationDialog", "Elevation (m)"))
        self.camera.setText(_translate("ConfigurationDialog", "Camera"))
        self.label_shift.setToolTip(_translate("ConfigurationDialog", "0. for tile numbers to be centered in tiles. Larger values may be needed to avoid cluttering. Must be between 0. and 1. (0.8 recommended)"))
        self.label_shift.setText(_translate("ConfigurationDialog", "Label shift parameter"))
        self.protocol_level.setToolTip(_translate("ConfigurationDialog", "Level of detail for session protocol (0 = no protocol, 3 = max. details)"))
        self.protocol_level.setText(_translate("ConfigurationDialog", "Session protocol level"))
        self.ALIGNMENT.setText(_translate("ConfigurationDialog", "ALIGNMENT"))
        self.new_camera.setToolTip(_translate("ConfigurationDialog", "Enter parameters for new camera"))
        self.new_camera.setText(_translate("ConfigurationDialog", "New"))
        self.delete_camera.setToolTip(_translate("ConfigurationDialog", "Remove currently selected camera from list"))
        self.delete_camera.setText(_translate("ConfigurationDialog", "Del"))
        self.geographical_position.setText(_translate("ConfigurationDialog", "Geographical Position"))
        self.edit_camera.setToolTip(_translate("ConfigurationDialog", "Edit parameters of currently selected camera"))
        self.edit_camera.setText(_translate("ConfigurationDialog", "Edit"))
        self.focal_length.setToolTip(_translate("ConfigurationDialog", "Focal length of telescope system, including projection lens. Must be between 0. and 100000."))
        self.focal_length.setText(_translate("ConfigurationDialog", "Focal length (mm)"))
        self.latitude.setToolTip(_translate("ConfigurationDialog", "Geographical latitude, positive towards north, in degrees plus decimal fraction. Must be between -90. and 90."))
        self.latitude.setText(_translate("ConfigurationDialog", "Latitude (degrees)"))
        self.fig_size_vertical.setToolTip(_translate("ConfigurationDialog", "Vertical dimension of tile visualization window in inches. Must be between 0. and 25."))
        self.fig_size_vertical.setText(_translate("ConfigurationDialog", "Figure size vertical (inch)"))
        self.workflow.setText(_translate("ConfigurationDialog", "Workflow"))
        self.camera_chooser.setToolTip(_translate("ConfigurationDialog", "List of cameras for which parameters have been entered"))
        self.max_autoalign_interval.setToolTip(_translate("ConfigurationDialog", "Maximum time between auto-alignments (s). Must be between 30. and 3600."))
        self.max_autoalign_interval.setText(_translate("ConfigurationDialog", "Maximum auto-alignment interval (s)    "))
        self.label_font_size.setToolTip(_translate("ConfigurationDialog", "Font size for tile numbers in visualization window. Must be between 6 and 16"))
        self.label_font_size.setText(_translate("ConfigurationDialog", "Font size for labels (points)"))
        self.telescope_interface.setToolTip(_translate("ConfigurationDialog", "Type of the mount interface (ASCOM or INDI)"))
        self.telescope_interface.setText(_translate("ConfigurationDialog", "Telescope mount interface"))
        self.mount_interface_chooser.setToolTip(_translate("ConfigurationDialog", "Select the type of the telescope mount interface"))
        self.configure_mount_interface.setToolTip(_translate("ConfigurationDialog", "Select the mount driver and configure parameters"))
        self.configure_mount_interface.setText(_translate("ConfigurationDialog", "Configure"))
        self.ip_address.setToolTip(_translate("ConfigurationDialog", "Address of system where FireCapture is executed. Either a valid IP address or \'localhost\'. Make sure the firewall is open for port 9820."))
        self.ip_address.setText(_translate("ConfigurationDialog", "IP address to access FireCapture"))
        self.timezone_chooser.setToolTip(_translate("ConfigurationDialog", "List of supported time zones"))
        self.protocol_level_chooser.setToolTip(_translate("ConfigurationDialog", "0: no protocol; 1: minimal output; 2: good coverage of workflow (recommended); 3: debug level"))
        self.buttonBox.setToolTip(_translate("ConfigurationDialog", "Save all parameters to configuration file or discard all changes"))

