# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drift_rate_dialog.ui'
#
# Created: Sun Apr 10 08:48:59 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DriftRateDialog(object):
    def setupUi(self, DriftRateDialog):
        DriftRateDialog.setObjectName(_fromUtf8("DriftRateDialog"))
        DriftRateDialog.resize(962, 670)
        font = QtGui.QFont()
        font.setPointSize(10)
        DriftRateDialog.setFont(font)
        DriftRateDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtGui.QGridLayout(DriftRateDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(DriftRateDialog)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(345, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(345, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.labelAlignmentList = QtGui.QLabel(DriftRateDialog)
        self.labelAlignmentList.setMinimumSize(QtCore.QSize(450, 35))
        self.labelAlignmentList.setMaximumSize(QtCore.QSize(450, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlignmentList.setFont(font)
        self.labelAlignmentList.setObjectName(_fromUtf8("labelAlignmentList"))
        self.gridLayout.addWidget(self.labelAlignmentList, 1, 0, 1, 3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.defaultLastRadioButton = QtGui.QRadioButton(DriftRateDialog)
        self.defaultLastRadioButton.setObjectName(_fromUtf8("defaultLastRadioButton"))
        self.gridLayout_2.addWidget(self.defaultLastRadioButton, 2, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DriftRateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 41))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 12, 2, 1, 1)
        self.spinBoxLastIndex = QtGui.QSpinBox(DriftRateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxLastIndex.sizePolicy().hasHeightForWidth())
        self.spinBoxLastIndex.setSizePolicy(sizePolicy)
        self.spinBoxLastIndex.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxLastIndex.setObjectName(_fromUtf8("spinBoxLastIndex"))
        self.gridLayout_2.addWidget(self.spinBoxLastIndex, 5, 2, 1, 1)
        self.labelFirstIndex = QtGui.QLabel(DriftRateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFirstIndex.sizePolicy().hasHeightForWidth())
        self.labelFirstIndex.setSizePolicy(sizePolicy)
        self.labelFirstIndex.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirstIndex.setFont(font)
        self.labelFirstIndex.setObjectName(_fromUtf8("labelFirstIndex"))
        self.gridLayout_2.addWidget(self.labelFirstIndex, 4, 1, 1, 1)
        self.line_2 = QtGui.QFrame(DriftRateDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 10, 1, 1, 2)
        self.noRadioButton = QtGui.QRadioButton(DriftRateDialog)
        self.noRadioButton.setMinimumSize(QtCore.QSize(0, 50))
        self.noRadioButton.setAutoExclusive(False)
        self.noRadioButton.setObjectName(_fromUtf8("noRadioButton"))
        self.gridLayout_2.addWidget(self.noRadioButton, 0, 1, 1, 2)
        self.defaultFirstRadioButton = QtGui.QRadioButton(DriftRateDialog)
        self.defaultFirstRadioButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.defaultFirstRadioButton.setFont(font)
        self.defaultFirstRadioButton.setAutoExclusive(False)
        self.defaultFirstRadioButton.setObjectName(_fromUtf8("defaultFirstRadioButton"))
        self.gridLayout_2.addWidget(self.defaultFirstRadioButton, 2, 1, 1, 1)
        self.line = QtGui.QFrame(DriftRateDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 2)
        self.spinBoxFirstIndex = QtGui.QSpinBox(DriftRateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFirstIndex.sizePolicy().hasHeightForWidth())
        self.spinBoxFirstIndex.setSizePolicy(sizePolicy)
        self.spinBoxFirstIndex.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxFirstIndex.setObjectName(_fromUtf8("spinBoxFirstIndex"))
        self.gridLayout_2.addWidget(self.spinBoxFirstIndex, 5, 1, 1, 1)
        self.labelLastIndex = QtGui.QLabel(DriftRateDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLastIndex.sizePolicy().hasHeightForWidth())
        self.labelLastIndex.setSizePolicy(sizePolicy)
        self.labelLastIndex.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLastIndex.setFont(font)
        self.labelLastIndex.setObjectName(_fromUtf8("labelLastIndex"))
        self.gridLayout_2.addWidget(self.labelLastIndex, 4, 2, 1, 1)
        self.mplwidget = MatplotlibWidget(DriftRateDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mplwidget.setFont(font)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout_2.addWidget(self.mplwidget, 11, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 2, 1, 1)

        self.retranslateUi(DriftRateDialog)
        QtCore.QObject.connect(self.defaultFirstRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelFirstIndex.setDisabled)
        QtCore.QObject.connect(self.defaultLastRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelLastIndex.setDisabled)
        QtCore.QObject.connect(self.defaultFirstRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxFirstIndex.setDisabled)
        QtCore.QObject.connect(self.defaultLastRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxLastIndex.setDisabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DriftRateDialog.close)
        QtCore.QObject.connect(self.spinBoxFirstIndex, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DriftRateDialog.setFocus)
        QtCore.QObject.connect(self.spinBoxLastIndex, QtCore.SIGNAL(_fromUtf8("editingFinished()")), DriftRateDialog.setFocus)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.defaultFirstRadioButton.setDisabled)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.defaultLastRadioButton.setDisabled)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelLastIndex.setDisabled)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxFirstIndex.setDisabled)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBoxLastIndex.setDisabled)
        QtCore.QObject.connect(self.noRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelFirstIndex.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(DriftRateDialog)

    def retranslateUi(self, DriftRateDialog):
        DriftRateDialog.setWindowTitle(_translate("DriftRateDialog", "Compute Drift Rate", None))
        self.tableWidget.setToolTip(_translate("DriftRateDialog", "Table with alignment points since start of program", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DriftRateDialog", "Time", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DriftRateDialog", "Ra (\')", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DriftRateDialog", "De (\')", None))
        self.labelAlignmentList.setText(_translate("DriftRateDialog", "List of Alignment Points since Start of Program", None))
        self.defaultLastRadioButton.setToolTip(_translate("DriftRateDialog", "If selected, the drift rate is always computed using the last alignment point.", None))
        self.defaultLastRadioButton.setText(_translate("DriftRateDialog", "Use last alignment point as default\n"
"end time for drift computation - L", None))
        self.defaultLastRadioButton.setShortcut(_translate("DriftRateDialog", "L", None))
        self.buttonBox.setToolTip(_translate("DriftRateDialog", "Set drift rate as selected or exit without change", None))
        self.spinBoxLastIndex.setToolTip(_translate("DriftRateDialog", "Spin box for the selection of the second alignment point for drift rate computation", None))
        self.labelFirstIndex.setToolTip(_translate("DriftRateDialog", "Shortcut A sets the focus on the first spin box.", None))
        self.labelFirstIndex.setText(_translate("DriftRateDialog", "Choose alignment point index\n"
"for begin of drift computation - A", None))
        self.noRadioButton.setToolTip(_translate("DriftRateDialog", "Disable application of drift correction", None))
        self.noRadioButton.setText(_translate("DriftRateDialog", "No drift correction - N", None))
        self.noRadioButton.setShortcut(_translate("DriftRateDialog", "N", None))
        self.defaultFirstRadioButton.setToolTip(_translate("DriftRateDialog", "If selected, the drift rate is always computed using the first alignment point.\n"
"Be sure that the orientation of the mounting has not changed since the first alignment.", None))
        self.defaultFirstRadioButton.setText(_translate("DriftRateDialog", "Use first alignment point as default\n"
"start time for drift computation - F", None))
        self.defaultFirstRadioButton.setShortcut(_translate("DriftRateDialog", "F", None))
        self.spinBoxFirstIndex.setToolTip(_translate("DriftRateDialog", "Spin box for the selection of the first alignment point for drift rate computation", None))
        self.labelLastIndex.setToolTip(_translate("DriftRateDialog", "Shortcut B sets the focus on the second spin box.", None))
        self.labelLastIndex.setText(_translate("DriftRateDialog", "Choose alignment point index\n"
"for end of drift computation - B", None))

from matplotlibwidget import MatplotlibWidget
