# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drift_rate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DriftRateDialog(object):
    def setupUi(self, DriftRateDialog):
        DriftRateDialog.setObjectName("DriftRateDialog")
        DriftRateDialog.resize(962, 670)
        font = QtGui.QFont()
        font.setPointSize(10)
        DriftRateDialog.setFont(font)
        DriftRateDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(DriftRateDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(DriftRateDialog)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setMinimumSize(QtCore.QSize(345, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(345, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.labelAlignmentList = QtWidgets.QLabel(DriftRateDialog)
        self.labelAlignmentList.setMinimumSize(QtCore.QSize(450, 35))
        self.labelAlignmentList.setMaximumSize(QtCore.QSize(450, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAlignmentList.setFont(font)
        self.labelAlignmentList.setObjectName("labelAlignmentList")
        self.gridLayout.addWidget(self.labelAlignmentList, 1, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.defaultLastRadioButton = QtWidgets.QRadioButton(DriftRateDialog)
        self.defaultLastRadioButton.setObjectName("defaultLastRadioButton")
        self.gridLayout_2.addWidget(self.defaultLastRadioButton, 2, 2, 1, 1)
        self.noRadioButton = QtWidgets.QRadioButton(DriftRateDialog)
        self.noRadioButton.setMinimumSize(QtCore.QSize(0, 50))
        self.noRadioButton.setAutoExclusive(False)
        self.noRadioButton.setObjectName("noRadioButton")
        self.gridLayout_2.addWidget(self.noRadioButton, 0, 1, 1, 2)
        self.defaultFirstRadioButton = QtWidgets.QRadioButton(DriftRateDialog)
        self.defaultFirstRadioButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.defaultFirstRadioButton.setFont(font)
        self.defaultFirstRadioButton.setAutoExclusive(False)
        self.defaultFirstRadioButton.setObjectName("defaultFirstRadioButton")
        self.gridLayout_2.addWidget(self.defaultFirstRadioButton, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(DriftRateDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 1, 2)
        self.spinBoxFirstIndex = QtWidgets.QSpinBox(DriftRateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFirstIndex.sizePolicy().hasHeightForWidth())
        self.spinBoxFirstIndex.setSizePolicy(sizePolicy)
        self.spinBoxFirstIndex.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxFirstIndex.setObjectName("spinBoxFirstIndex")
        self.gridLayout_2.addWidget(self.spinBoxFirstIndex, 5, 1, 1, 1)
        self.labelLastIndex = QtWidgets.QLabel(DriftRateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLastIndex.sizePolicy().hasHeightForWidth())
        self.labelLastIndex.setSizePolicy(sizePolicy)
        self.labelLastIndex.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelLastIndex.setFont(font)
        self.labelLastIndex.setObjectName("labelLastIndex")
        self.gridLayout_2.addWidget(self.labelLastIndex, 4, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DriftRateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 41))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 12, 2, 1, 1)
        self.spinBoxLastIndex = QtWidgets.QSpinBox(DriftRateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxLastIndex.sizePolicy().hasHeightForWidth())
        self.spinBoxLastIndex.setSizePolicy(sizePolicy)
        self.spinBoxLastIndex.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxLastIndex.setObjectName("spinBoxLastIndex")
        self.gridLayout_2.addWidget(self.spinBoxLastIndex, 5, 2, 1, 1)
        self.labelFirstIndex = QtWidgets.QLabel(DriftRateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFirstIndex.sizePolicy().hasHeightForWidth())
        self.labelFirstIndex.setSizePolicy(sizePolicy)
        self.labelFirstIndex.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFirstIndex.setFont(font)
        self.labelFirstIndex.setObjectName("labelFirstIndex")
        self.gridLayout_2.addWidget(self.labelFirstIndex, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(DriftRateDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 10, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.mpl_placeholder = QtWidgets.QLabel(DriftRateDialog)
        self.mpl_placeholder.setObjectName("mpl_placeholder")
        self.gridLayout_2.addWidget(self.mpl_placeholder, 11, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 2, 1, 1)

        self.retranslateUi(DriftRateDialog)
        self.defaultFirstRadioButton.toggled['bool'].connect(self.labelFirstIndex.setDisabled)
        self.defaultLastRadioButton.toggled['bool'].connect(self.labelLastIndex.setDisabled)
        self.defaultFirstRadioButton.toggled['bool'].connect(self.spinBoxFirstIndex.setDisabled)
        self.defaultLastRadioButton.toggled['bool'].connect(self.spinBoxLastIndex.setDisabled)
        self.buttonBox.rejected.connect(DriftRateDialog.close)
        self.spinBoxFirstIndex.editingFinished.connect(DriftRateDialog.setFocus)
        self.spinBoxLastIndex.editingFinished.connect(DriftRateDialog.setFocus)
        self.noRadioButton.toggled['bool'].connect(self.defaultFirstRadioButton.setDisabled)
        self.noRadioButton.toggled['bool'].connect(self.defaultLastRadioButton.setDisabled)
        self.noRadioButton.toggled['bool'].connect(self.labelLastIndex.setDisabled)
        self.noRadioButton.toggled['bool'].connect(self.spinBoxFirstIndex.setDisabled)
        self.noRadioButton.toggled['bool'].connect(self.spinBoxLastIndex.setDisabled)
        self.noRadioButton.toggled['bool'].connect(self.labelFirstIndex.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(DriftRateDialog)

    def retranslateUi(self, DriftRateDialog):
        _translate = QtCore.QCoreApplication.translate
        DriftRateDialog.setWindowTitle(_translate("DriftRateDialog", "Compute Drift Rate"))
        self.tableWidget.setToolTip(_translate("DriftRateDialog", "Table with alignment points since start of program"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DriftRateDialog", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DriftRateDialog", "Ra (\')"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DriftRateDialog", "De (\')"))
        self.labelAlignmentList.setText(_translate("DriftRateDialog", "List of Alignment Points since Start of Program"))
        self.defaultLastRadioButton.setToolTip(_translate("DriftRateDialog", "If selected, the drift rate is always computed using the last alignment point."))
        self.defaultLastRadioButton.setText(_translate("DriftRateDialog", "Use last alignment point as default\n"
"end time for drift computation - L"))
        self.defaultLastRadioButton.setShortcut(_translate("DriftRateDialog", "L"))
        self.noRadioButton.setToolTip(_translate("DriftRateDialog", "Disable application of drift correction"))
        self.noRadioButton.setText(_translate("DriftRateDialog", "No drift correction - N"))
        self.noRadioButton.setShortcut(_translate("DriftRateDialog", "N"))
        self.defaultFirstRadioButton.setToolTip(_translate("DriftRateDialog", "If selected, the drift rate is always computed using the first alignment point.\n"
"Be sure that the orientation of the mounting has not changed since the first alignment."))
        self.defaultFirstRadioButton.setText(_translate("DriftRateDialog", "Use first alignment point as default\n"
"start time for drift computation - F"))
        self.defaultFirstRadioButton.setShortcut(_translate("DriftRateDialog", "F"))
        self.spinBoxFirstIndex.setToolTip(_translate("DriftRateDialog", "Spin box for the selection of the first alignment point for drift rate computation"))
        self.labelLastIndex.setToolTip(_translate("DriftRateDialog", "Shortcut B sets the focus on the second spin box."))
        self.labelLastIndex.setText(_translate("DriftRateDialog", "Choose alignment point index\n"
"for end of drift computation - B"))
        self.buttonBox.setToolTip(_translate("DriftRateDialog", "Set drift rate as selected or exit without change"))
        self.spinBoxLastIndex.setToolTip(_translate("DriftRateDialog", "Spin box for the selection of the second alignment point for drift rate computation"))
        self.labelFirstIndex.setToolTip(_translate("DriftRateDialog", "Shortcut A sets the focus on the first spin box."))
        self.labelFirstIndex.setText(_translate("DriftRateDialog", "Choose alignment point index\n"
"for begin of drift computation - A"))
        self.mpl_placeholder.setText(_translate("DriftRateDialog", "Matplotlib window placeholder"))

