# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indi_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_INDIDialog(object):
    def setupUi(self, INDIDialog):
        INDIDialog.setObjectName("INDIDialog")
        INDIDialog.resize(542, 323)
        INDIDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(INDIDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(INDIDialog)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 522, 275))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 511, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_guiding_interval = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_guiding_interval.setFont(font)
        self.input_guiding_interval.setObjectName("input_guiding_interval")
        self.gridLayout.addWidget(self.input_guiding_interval, 4, 1, 1, 1)
        self.pulse_guide_speed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse_guide_speed.setFont(font)
        self.pulse_guide_speed.setObjectName("pulse_guide_speed")
        self.gridLayout.addWidget(self.pulse_guide_speed, 3, 0, 1, 1)
        self.input_indi_server_url = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_indi_server_url.setFont(font)
        self.input_indi_server_url.setObjectName("input_indi_server_url")
        self.gridLayout.addWidget(self.input_indi_server_url, 2, 1, 1, 1)
        self.configure_server = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.configure_server.setFont(font)
        self.configure_server.setObjectName("configure_server")
        self.gridLayout.addWidget(self.configure_server, 0, 0, 1, 2)
        self.guiding_interval = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.guiding_interval.setFont(font)
        self.guiding_interval.setObjectName("guiding_interval")
        self.gridLayout.addWidget(self.guiding_interval, 4, 0, 1, 1)
        self.wait_interval = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wait_interval.setFont(font)
        self.wait_interval.setObjectName("wait_interval")
        self.gridLayout.addWidget(self.wait_interval, 5, 0, 1, 1)
        self.input_wait_interval = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_wait_interval.setFont(font)
        self.input_wait_interval.setObjectName("input_wait_interval")
        self.gridLayout.addWidget(self.input_wait_interval, 5, 1, 1, 1)
        self.indi_server_url = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indi_server_url.setFont(font)
        self.indi_server_url.setObjectName("indi_server_url")
        self.gridLayout.addWidget(self.indi_server_url, 2, 0, 1, 1)
        self.pulse_guide_speed_chooser = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pulse_guide_speed_chooser.setFont(font)
        self.pulse_guide_speed_chooser.setObjectName("pulse_guide_speed_chooser")
        self.gridLayout.addWidget(self.pulse_guide_speed_chooser, 3, 1, 1, 1)
        self.telescope_lookup_precision = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.telescope_lookup_precision.setFont(font)
        self.telescope_lookup_precision.setObjectName("telescope_lookup_precision")
        self.gridLayout.addWidget(self.telescope_lookup_precision, 6, 0, 1, 1)
        self.input_telescope_lookup_precision = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_telescope_lookup_precision.setFont(font)
        self.input_telescope_lookup_precision.setObjectName("input_telescope_lookup_precision")
        self.gridLayout.addWidget(self.input_telescope_lookup_precision, 6, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(INDIDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(INDIDialog)
        self.buttonBox.accepted.connect(INDIDialog.accept)
        self.buttonBox.rejected.connect(INDIDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(INDIDialog)
        INDIDialog.setTabOrder(self.scrollArea, self.configure_server)
        INDIDialog.setTabOrder(self.configure_server, self.input_indi_server_url)
        INDIDialog.setTabOrder(self.input_indi_server_url, self.pulse_guide_speed_chooser)
        INDIDialog.setTabOrder(self.pulse_guide_speed_chooser, self.input_guiding_interval)
        INDIDialog.setTabOrder(self.input_guiding_interval, self.input_wait_interval)

    def retranslateUi(self, INDIDialog):
        _translate = QtCore.QCoreApplication.translate
        INDIDialog.setWindowTitle(_translate("INDIDialog", "Configure INDI telescope interface"))
        self.pulse_guide_speed.setToolTip(_translate("INDIDialog", "Speed of pulse guide operations."))
        self.pulse_guide_speed.setText(_translate("INDIDialog", "Pulse guide speed"))
        self.configure_server.setToolTip(_translate("INDIDialog", "Make sure to enter the URL where the server is running below."))
        self.configure_server.setText(_translate("INDIDialog", "Start / configure INDI server and select telescope driver"))
        self.guiding_interval.setToolTip(_translate("INDIDialog", "Duration of guiding pulses during video exposure, e.g. 0.2. Must be between 0. and 3."))
        self.guiding_interval.setText(_translate("INDIDialog", "Guide pulse duration (s)"))
        self.wait_interval.setToolTip(_translate("INDIDialog", "Parameter to reduce polling frequency during telescope slewing, e.g. 1. Must be between 0. and 20."))
        self.wait_interval.setText(_translate("INDIDialog", "Wait interval (s)"))
        self.indi_server_url.setToolTip(_translate("INDIDialog", "Enter either \'localhost\' or a valid IP address."))
        self.indi_server_url.setText(_translate("INDIDialog", "URL of the INDI server"))
        self.telescope_lookup_precision.setToolTip(_translate("INDIDialog", "Required precision (\") for lookup of telescope position. Must be between 0.1 and 10."))
        self.telescope_lookup_precision.setText(_translate("INDIDialog", "Telescope position lookup precision (\")   "))
        self.buttonBox.setToolTip(_translate("INDIDialog", "Save or discard new input"))

