# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtgui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 252)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.new_landmark_selection = QtWidgets.QPushButton(self.centralwidget)
        self.new_landmark_selection.setObjectName("new_landmark_selection")
        self.gridLayout.addWidget(self.new_landmark_selection, 4, 0, 1, 1)
        self.restart = QtWidgets.QPushButton(self.centralwidget)
        self.restart.setObjectName("restart")
        self.gridLayout.addWidget(self.restart, 0, 0, 1, 1)
        self.set_all_tiles_unprocessed = QtWidgets.QPushButton(self.centralwidget)
        self.set_all_tiles_unprocessed.setObjectName("set_all_tiles_unprocessed")
        self.gridLayout.addWidget(self.set_all_tiles_unprocessed, 4, 6, 1, 1)
        self.set_focus_area = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.set_focus_area.setFont(font)
        self.set_focus_area.setObjectName("set_focus_area")
        self.gridLayout.addWidget(self.set_focus_area, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 7, 1)
        self.set_tile_unprocessed = QtWidgets.QPushButton(self.centralwidget)
        self.set_tile_unprocessed.setObjectName("set_tile_unprocessed")
        self.gridLayout.addWidget(self.set_tile_unprocessed, 4, 5, 1, 1)
        self.select_tile = QtWidgets.QPushButton(self.centralwidget)
        self.select_tile.setObjectName("select_tile")
        self.gridLayout.addWidget(self.select_tile, 2, 5, 1, 1)
        self.move_to_selected_tile = QtWidgets.QPushButton(self.centralwidget)
        self.move_to_selected_tile.setObjectName("move_to_selected_tile")
        self.gridLayout.addWidget(self.move_to_selected_tile, 2, 6, 1, 1)
        self.set_all_tiles_processed = QtWidgets.QPushButton(self.centralwidget)
        self.set_all_tiles_processed.setObjectName("set_all_tiles_processed")
        self.gridLayout.addWidget(self.set_all_tiles_processed, 6, 6, 1, 1)
        self.edit_configuration = QtWidgets.QPushButton(self.centralwidget)
        self.edit_configuration.setObjectName("edit_configuration")
        self.gridLayout.addWidget(self.edit_configuration, 0, 1, 1, 1)
        self.start_continue_recording = QtWidgets.QPushButton(self.centralwidget)
        self.start_continue_recording.setObjectName("start_continue_recording")
        self.gridLayout.addWidget(self.start_continue_recording, 0, 5, 1, 2)
        self.configure_drift_correction = QtWidgets.QPushButton(self.centralwidget)
        self.configure_drift_correction.setObjectName("configure_drift_correction")
        self.gridLayout.addWidget(self.configure_drift_correction, 4, 3, 1, 1)
        self.alignment = QtWidgets.QPushButton(self.centralwidget)
        self.alignment.setEnabled(True)
        self.alignment.setObjectName("alignment")
        self.gridLayout.addWidget(self.alignment, 0, 3, 1, 1)
        self.autoalignment = QtWidgets.QPushButton(self.centralwidget)
        self.autoalignment.setObjectName("autoalignment")
        self.gridLayout.addWidget(self.autoalignment, 2, 3, 1, 1)
        self.set_tile_processed = QtWidgets.QPushButton(self.centralwidget)
        self.set_tile_processed.setObjectName("set_tile_processed")
        self.gridLayout.addWidget(self.set_tile_processed, 6, 5, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 0, 1, 2)
        self.goto_focus_area = QtWidgets.QPushButton(self.centralwidget)
        self.goto_focus_area.setObjectName("goto_focus_area")
        self.gridLayout.addWidget(self.goto_focus_area, 6, 1, 1, 1)
        self.show_landmark = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.show_landmark.setFont(font)
        self.show_landmark.setObjectName("show_landmark")
        self.gridLayout.addWidget(self.show_landmark, 4, 1, 1, 1)
        self.rotate_camera = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_camera.setObjectName("rotate_camera")
        self.gridLayout.addWidget(self.rotate_camera, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 7, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setLineWidth(1)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 5, 1, 2)
        self.prompt_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prompt_text_browser.setFont(font)
        self.prompt_text_browser.setLineWidth(1)
        self.prompt_text_browser.setMidLineWidth(0)
        self.prompt_text_browser.setUndoRedoEnabled(True)
        self.prompt_text_browser.setObjectName("prompt_text_browser")
        self.gridLayout.addWidget(self.prompt_text_browser, 7, 0, 1, 7)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 5, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.restart, self.edit_configuration)
        MainWindow.setTabOrder(self.edit_configuration, self.rotate_camera)
        MainWindow.setTabOrder(self.rotate_camera, self.new_landmark_selection)
        MainWindow.setTabOrder(self.new_landmark_selection, self.show_landmark)
        MainWindow.setTabOrder(self.show_landmark, self.set_focus_area)
        MainWindow.setTabOrder(self.set_focus_area, self.goto_focus_area)
        MainWindow.setTabOrder(self.goto_focus_area, self.alignment)
        MainWindow.setTabOrder(self.alignment, self.autoalignment)
        MainWindow.setTabOrder(self.autoalignment, self.configure_drift_correction)
        MainWindow.setTabOrder(self.configure_drift_correction, self.start_continue_recording)
        MainWindow.setTabOrder(self.start_continue_recording, self.select_tile)
        MainWindow.setTabOrder(self.select_tile, self.move_to_selected_tile)
        MainWindow.setTabOrder(self.move_to_selected_tile, self.set_tile_unprocessed)
        MainWindow.setTabOrder(self.set_tile_unprocessed, self.set_all_tiles_unprocessed)
        MainWindow.setTabOrder(self.set_all_tiles_unprocessed, self.set_tile_processed)
        MainWindow.setTabOrder(self.set_tile_processed, self.set_all_tiles_processed)
        MainWindow.setTabOrder(self.set_all_tiles_processed, self.prompt_text_browser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MoonPanoramaMaker"))
        self.new_landmark_selection.setToolTip(_translate("MainWindow", "Select a new landmark for mount alignment"))
        self.new_landmark_selection.setText(_translate("MainWindow", "Select new landmark - L"))
        self.new_landmark_selection.setShortcut(_translate("MainWindow", "L"))
        self.restart.setToolTip(_translate("MainWindow", "Restart the whole workflow (new tile layout)"))
        self.restart.setText(_translate("MainWindow", "Restart - R"))
        self.restart.setShortcut(_translate("MainWindow", "R"))
        self.set_all_tiles_unprocessed.setToolTip(_translate("MainWindow", "Mark all tiles as unprocessed"))
        self.set_all_tiles_unprocessed.setText(_translate("MainWindow", "Mark all tiles unprocessed - V"))
        self.set_all_tiles_unprocessed.setShortcut(_translate("MainWindow", "V"))
        self.set_focus_area.setToolTip(_translate("MainWindow", "Mark current location for setting the telescope focus"))
        self.set_focus_area.setText(_translate("MainWindow", "Select focus area - F"))
        self.set_focus_area.setShortcut(_translate("MainWindow", "F"))
        self.set_tile_unprocessed.setToolTip(_translate("MainWindow", "Remove current tile number from list of processed tiles"))
        self.set_tile_unprocessed.setText(_translate("MainWindow", "Mark tile(s) unprocessed - U"))
        self.set_tile_unprocessed.setShortcut(_translate("MainWindow", "U"))
        self.select_tile.setToolTip(_translate("MainWindow", "Select the number of a single tile"))
        self.select_tile.setText(_translate("MainWindow", "Select tile - T"))
        self.select_tile.setShortcut(_translate("MainWindow", "T"))
        self.move_to_selected_tile.setToolTip(_translate("MainWindow", "Move the telescope to the selected tile"))
        self.move_to_selected_tile.setText(_translate("MainWindow", "Move to selected tile - M"))
        self.move_to_selected_tile.setShortcut(_translate("MainWindow", "M"))
        self.set_all_tiles_processed.setToolTip(_translate("MainWindow", "Mark all tiles as processed"))
        self.set_all_tiles_processed.setText(_translate("MainWindow", "Mark all tiles processed - Q"))
        self.set_all_tiles_processed.setShortcut(_translate("MainWindow", "Q"))
        self.edit_configuration.setToolTip(_translate("MainWindow", "Set configuration parameters for location, equipment and program execution"))
        self.edit_configuration.setText(_translate("MainWindow", "Edit configuration - C"))
        self.edit_configuration.setShortcut(_translate("MainWindow", "C"))
        self.start_continue_recording.setToolTip(_translate("MainWindow", "Continue recording with next unprocessed tile"))
        self.start_continue_recording.setText(_translate("MainWindow", "Start / continue recording - S"))
        self.start_continue_recording.setShortcut(_translate("MainWindow", "S"))
        self.configure_drift_correction.setToolTip(_translate("MainWindow", "Select alignment points for drift computation and compensation"))
        self.configure_drift_correction.setText(_translate("MainWindow", "Configure drift correction - D"))
        self.configure_drift_correction.setShortcut(_translate("MainWindow", "D"))
        self.alignment.setToolTip(_translate("MainWindow", "Align (or re-align) telescope with landmark"))
        self.alignment.setText(_translate("MainWindow", "Align mount - A"))
        self.alignment.setShortcut(_translate("MainWindow", "A"))
        self.autoalignment.setToolTip(_translate("MainWindow", "Switch on / off auto-alignment"))
        self.autoalignment.setText(_translate("MainWindow", "Switch on Auto-alignment - B"))
        self.autoalignment.setShortcut(_translate("MainWindow", "B"))
        self.set_tile_processed.setToolTip(_translate("MainWindow", "Add current tile number to list of processed tiles"))
        self.set_tile_processed.setText(_translate("MainWindow", "Mark tile(s) processed - P"))
        self.set_tile_processed.setShortcut(_translate("MainWindow", "P"))
        self.goto_focus_area.setToolTip(_translate("MainWindow", "Move the telescope for focus adjustment"))
        self.goto_focus_area.setText(_translate("MainWindow", "GoTo focus area - G"))
        self.goto_focus_area.setShortcut(_translate("MainWindow", "G"))
        self.show_landmark.setToolTip(_translate("MainWindow", "Show a picture of the landmark currently selected "))
        self.show_landmark.setText(_translate("MainWindow", "Show landmark - K"))
        self.show_landmark.setShortcut(_translate("MainWindow", "K"))
        self.rotate_camera.setToolTip(_translate("MainWindow", "Rotate camera until the moon limb stands vertically at FOV center"))
        self.rotate_camera.setText(_translate("MainWindow", "Adjust camera orientation - O"))
        self.rotate_camera.setShortcut(_translate("MainWindow", "O"))
        self.prompt_text_browser.setToolTip(_translate("MainWindow", "Window to show user instructions"))

